apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: '1.17.5'
  values:
    kubeProxyReplacement: true
    image:
      pullPolicy: IfNotPresent
    ipam:
      mode: kubernetes
