run:
  timeout: 5m

version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

issues:
  exclude-dirs:
    - vendor
  exclude-case-sensitive: false
  exclude-use-default: true
