version: 2

project_name: shoulders

before:
  hooks:
    - cd shoulders-cli && go mod tidy

builds:
  - main: ./shoulders-cli
    binary: shoulders
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: jherreros
    name: shoulders

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
