apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: topic
spec:
  schema:
    apiVersion: v1alpha1
    kind: Topic
    spec:
      name: string
      namespace: string
  resources:
    - id: topic
      template:
        apiVersion: kafka.strimzi.io/v1beta2
        kind: KafkaTopic
        metadata:
          name: ${schema.spec.name}-topic
          namespace: ${schema.spec.namespace}
          labels:
            strimzi.io/cluster: my-cluster
        spec:
          partitions: 3
          replicas: 3
          config:
            retention.ms: 604800000  # 7 days
            segment.ms: 86400000     # 1 day
