apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx-namespace.yaml
  - kro-namespace.yaml
  - kyverno-namespace.yaml
  - strimzi-namespace.yaml
  - cnpg-namespace.yaml
  - kafka-namespace.yaml